name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip==20.2.4 poetry==1.1.4
        poetry config virtualenvs.create false
        poetry install
    - run: black --check ./
    - run: mypy *.py
    - run: pytest ./
